#!/usr/bin/env bash
# name: git-autocommit
# type: command
# description: Commit and push a Sancho repo. Files over 5 MB or binary (not on the allowlist) are unstaged and listed in GIT-EXCLUDED.md; everything else still commits. Quiet if nothing changed.
# why: Commits must not depend on anyone remembering (history is provenance), and one oversize file must never stall every commit (architecture §11, found 2026-09-30).
# reads: the worktree ($SANCHO_WORKTREE, default ~/Sync/Sancho); _queue/leases/ for the live-session list
# writes: a git commit; _setup/GIT-EXCLUDED.md (or GIT-EXCLUDED.md at the root when there is no _setup/); push to origin
# schedule: hourly + at login (com.sancho.autocommit); ~/Sancho-Private via com.sancho.autocommit-private
# test: _setup/tests/git-autocommit/
# RUN:  bash git-autocommit.sh [message prefix]      SANCHO_WORKTREE=~/Sancho-Private bash git-autocommit.sh

set -euo pipefail
WORKTREE="${SANCHO_WORKTREE:-$HOME/Sync/Sancho}"
MAX_BYTES=$((5 * 1024 * 1024))                       # same cap as hooks/pre-commit
ALLOW_BINARY_EXT='pdf|xlsx|docx|pptx|svg|woff|woff2' # same allowlist as hooks/pre-commit
cd "$WORKTREE"
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || { echo "not a git worktree: $WORKTREE"; exit 1; }

if [ -d _setup ]; then EXCL="_setup/GIT-EXCLUDED.md"; else EXCL="GIT-EXCLUDED.md"; fi
now=$(date "+%Y-%m-%d %H:%M")
has_head=0; git rev-parse -q --verify HEAD >/dev/null && has_head=1

git add -A

# Find offenders among staged adds/changes; unstage each without staging a deletion.
rows=""
while IFS= read -r -d '' path; do
  [ -f "$path" ] || continue
  size=$(wc -c < "$path" | tr -d ' ')
  reason=""
  if [ "$size" -gt "$MAX_BYTES" ]; then
    reason="over 5 MB"
  elif git diff --cached --numstat -- "$path" | grep -q '^-'; then
    ext="${path##*.}"
    echo "$ext" | grep -Eiq "^($ALLOW_BINARY_EXT)$" || reason="binary"
  fi
  [ -n "$reason" ] || continue
  if [ $has_head -eq 1 ] && git cat-file -e "HEAD:$path" 2>/dev/null; then
    git restore --staged -- "$path"
  else
    git rm --cached -q -- "$path"
  fi
  first=$(grep -F "| $path |" "$EXCL" 2>/dev/null | awk -F'|' '{gsub(/^ +| +$/,"",$5); print $5}' | head -1 || true)
  rows="${rows}| $path | $((size / 1024)) KB | $reason | ${first:-$now} |"$'\n'
done < <(git diff --cached --name-only -z --diff-filter=ACMR)

# Offenders already committed-around stay listed while they still exist and are untracked.
while IFS= read -r line; do
  p=$(echo "$line" | awk -F'|' '{gsub(/^ +| +$/,"",$2); print $2}')
  [ -n "$p" ] && [ -f "$p" ] || continue
  echo "$rows" | grep -qF "| $p |" && continue
  git ls-files --error-unmatch -- "$p" >/dev/null 2>&1 && continue
  rows="${rows}${line}"$'\n'
done < <(grep '^| ' "$EXCL" 2>/dev/null | grep -v '^| path |' || true)

new_excl="# GIT-EXCLUDED
generated by git-autocommit.sh · files kept in Sync but refused by git (over 5 MB, or binary). They are backed up by sync.com, not by git. Nothing is moved automatically.

| path | size | reason | first seen |
|---|---|---|---|
${rows:-| (none) | | | |
}"
if [ ! -f "$EXCL" ] || [ "$(cat "$EXCL")" != "$(printf '%s' "$new_excl")" ]; then
  printf '%s' "$new_excl" > "$EXCL"
fi
git add -- "$EXCL"

if git diff --cached --quiet; then
  echo "nothing to commit"
else
  stamp=$(date "+%Y-%m-%d %H:%M")
  changed=$(git diff --cached --name-only | wc -l | tr -d ' ')
  summary=$(git diff --cached --name-only | sed 's#^\([^/]*\)/.*#\1#' | sort | uniq -c | sort -rn | head -4 | awk '{printf "%s(%s) ", $2, $1}')
  sessions=""
  if [ -d _queue/leases ]; then
    sessions=$(find _queue/leases -maxdepth 1 -name '*.md' -exec basename {} .md \; 2>/dev/null | sort | paste -sd, - || true)
  fi
  msg="${1:-auto} $stamp: $changed files [$summary]"
  [ -n "$sessions" ] && msg="$msg sessions: $sessions"
  git commit -q -m "$msg"   # pre-commit hook still runs; it should find nothing now
  echo "committed: $msg"
fi
n_excl=$(echo -n "$rows" | grep -c '^| ' || true)
[ "$n_excl" -gt 0 ] && echo "excluded from git: $n_excl file(s), see $EXCL"

# Push whatever is unpushed, and say why when it fails (it failed silently 2026-09-22..30).
if git remote get-url origin >/dev/null 2>&1; then
  ahead=$(git rev-list --count '@{u}..HEAD' 2>/dev/null || echo "?")
  if [ "$ahead" != "0" ]; then
    if err=$(GIT_SSH_COMMAND="ssh -o BatchMode=yes -o ConnectTimeout=20" git push -q origin HEAD 2>&1); then
      echo "pushed ($ahead commit(s))"
    else
      echo "push failed: $(echo "$err" | head -1)"
      exit 2
    fi
  fi
fi
